<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Map [
<!ELEMENT Map (Comment?,Link*)>
<!ATTLIST Map
          InpDim       CDATA #REQUIRED
          OutDim       CDATA #REQUIRED
          LinkAttrDim  CDATA #REQUIRED>
<!ELEMENT Comment (#PCDATA)>
<!ELEMENT Link (InputNode+,OutputNode+,LinkAttr+)>
<!ELEMENT InputNode (Component+)>
<!ATTLIST InputNode
    Dim         CDATA #REQUIRED>
<!ELEMENT OutputNode (Component+)>
<!ATTLIST OutputNode
    Dim         CDATA #REQUIRED>
<!ELEMENT LinkAttr (LinkAttrValue+)>
<!ATTLIST LinkAttr
    Dim         CDATA #REQUIRED>
<!ELEMENT Component EMPTY>
<!ATTLIST Component
    Value         CDATA #REQUIRED
    NodeIdx       CDATA #REQUIRED>
<!ELEMENT LinkAttrValue EMPTY>
<!ATTLIST LinkAttrValue
    LinkValue     CDATA #REQUIRED
    Idx           CDATA #REQUIRED>
]>
<Map InpDim="4" OutDim="4" LinkAttrDim="1">
	<Comment>
[1,0,320,0,240][1,-60,60,-53,53]
	</Comment>
	<Link>
		<InputNode Dim="4">
			<Component Value="87.16" NodeIdx="0" />
			<Component Value="67.08" NodeIdx="1" />
			<Component Value="93" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-42.33" NodeIdx="0" />
			<Component Value="13.75" NodeIdx="1" />
			<Component Value="93" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="159.51" NodeIdx="0" />
			<Component Value="123.08" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="87.16" NodeIdx="0" />
			<Component Value="67.08" NodeIdx="1" />
			<Component Value="93" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-47.06" NodeIdx="0" />
			<Component Value="15.29" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="141.27" NodeIdx="0" />
			<Component Value="62.37" NodeIdx="1" />
			<Component Value="21" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-17.51" NodeIdx="0" />
			<Component Value="17.51" NodeIdx="1" />
			<Component Value="21" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="84.14" NodeIdx="0" />
			<Component Value="95.35" NodeIdx="1" />
			<Component Value="52" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-48.61" NodeIdx="0" />
			<Component Value="48.61" NodeIdx="1" />
			<Component Value="48" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="84.14" NodeIdx="0" />
			<Component Value="95.35" NodeIdx="1" />
			<Component Value="52" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-46.39" NodeIdx="0" />
			<Component Value="7.34" NodeIdx="1" />
			<Component Value="18" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="113.22" NodeIdx="0" />
			<Component Value="127.4" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-22.81" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="93.35" NodeIdx="0" />
			<Component Value="86.04" NodeIdx="1" />
			<Component Value="73" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-44.24" NodeIdx="0" />
			<Component Value="32.14" NodeIdx="1" />
			<Component Value="70" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="93.35" NodeIdx="0" />
			<Component Value="86.04" NodeIdx="1" />
			<Component Value="73" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-37" NodeIdx="0" />
			<Component Value="5.86" NodeIdx="1" />
			<Component Value="73" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="181.5" NodeIdx="0" />
			<Component Value="77.8" NodeIdx="1" />
			<Component Value="75" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="9.72" NodeIdx="0" />
			<Component Value="9.72" NodeIdx="1" />
			<Component Value="75" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="130.39" NodeIdx="0" />
			<Component Value="61.89" NodeIdx="1" />
			<Component Value="82" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-13.41" NodeIdx="0" />
			<Component Value="18.46" NodeIdx="1" />
			<Component Value="80" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="130.39" NodeIdx="0" />
			<Component Value="61.89" NodeIdx="1" />
			<Component Value="82" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-14.79" NodeIdx="0" />
			<Component Value="14.79" NodeIdx="1" />
			<Component Value="82" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="113.88" NodeIdx="0" />
			<Component Value="73.88" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-18.46" NodeIdx="0" />
			<Component Value="13.41" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="10" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="149.17" NodeIdx="0" />
			<Component Value="86.66" NodeIdx="1" />
			<Component Value="92" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-32.14" NodeIdx="0" />
			<Component Value="44.24" NodeIdx="1" />
			<Component Value="89" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="149.17" NodeIdx="0" />
			<Component Value="86.66" NodeIdx="1" />
			<Component Value="92" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-4.73" NodeIdx="0" />
			<Component Value="9.28" NodeIdx="1" />
			<Component Value="92" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="108.33" NodeIdx="0" />
			<Component Value="119.99" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-22.81" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="175.96" NodeIdx="0" />
			<Component Value="70.86" NodeIdx="1" />
			<Component Value="33" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="12.28" NodeIdx="0" />
			<Component Value="37.81" NodeIdx="1" />
			<Component Value="33" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="163.08" NodeIdx="0" />
			<Component Value="120.48" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="168.77" NodeIdx="0" />
			<Component Value="64.61" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-12.28" NodeIdx="0" />
			<Component Value="37.81" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="168.77" NodeIdx="0" />
			<Component Value="64.61" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="0" NodeIdx="0" />
			<Component Value="15.47" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="138.97" NodeIdx="0" />
			<Component Value="109.28" NodeIdx="1" />
			<Component Value="14" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="6.58" NodeIdx="0" />
			<Component Value="41.59" NodeIdx="1" />
			<Component Value="14" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="129.24" NodeIdx="0" />
			<Component Value="124.87" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-13.58" NodeIdx="0" />
			<Component Value="-2.15" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="13" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="141" NodeIdx="0" />
			<Component Value="113.82" NodeIdx="1" />
			<Component Value="17" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-8.38" NodeIdx="0" />
			<Component Value="2.72" NodeIdx="1" />
			<Component Value="17" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="84.41" NodeIdx="0" />
			<Component Value="81.48" NodeIdx="1" />
			<Component Value="18" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-46.39" NodeIdx="0" />
			<Component Value="7.34" NodeIdx="1" />
			<Component Value="18" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="132.67" NodeIdx="0" />
			<Component Value="120" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-13.58" NodeIdx="0" />
			<Component Value="-2.15" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="13" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="164.36" NodeIdx="0" />
			<Component Value="111.44" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="129.24" NodeIdx="0" />
			<Component Value="124.87" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-13.75" NodeIdx="0" />
			<Component Value="42.33" NodeIdx="1" />
			<Component Value="10" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="124.38" NodeIdx="0" />
			<Component Value="70.97" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-18.46" NodeIdx="0" />
			<Component Value="13.41" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="10" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="168.55" NodeIdx="0" />
			<Component Value="124.36" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="124.38" NodeIdx="0" />
			<Component Value="70.97" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-18.63" NodeIdx="0" />
			<Component Value="9.49" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="86.12" NodeIdx="0" />
			<Component Value="108.29" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-44.51" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="168.77" NodeIdx="0" />
			<Component Value="64.61" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="0" NodeIdx="0" />
			<Component Value="44.51" NodeIdx="1" />
			<Component Value="8" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="154.88" NodeIdx="0" />
			<Component Value="123.71" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="168.77" NodeIdx="0" />
			<Component Value="64.61" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="7.34" NodeIdx="0" />
			<Component Value="46.39" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="118.88" NodeIdx="0" />
			<Component Value="63.4" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-18.46" NodeIdx="0" />
			<Component Value="13.41" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="10" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="101.89" NodeIdx="0" />
			<Component Value="90.39" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-29.38" NodeIdx="0" />
			<Component Value="9.54" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160.48" NodeIdx="0" />
			<Component Value="116.91" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="180.59" NodeIdx="0" />
			<Component Value="91.64" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="7.34" NodeIdx="0" />
			<Component Value="46.39" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="181.02" NodeIdx="0" />
			<Component Value="109.28" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="7.16" NodeIdx="0" />
			<Component Value="1.13" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="101.89" NodeIdx="0" />
			<Component Value="90.39" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-28.44" NodeIdx="0" />
			<Component Value="4.5" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="161.41" NodeIdx="0" />
			<Component Value="117.22" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-33.21" NodeIdx="0" />
			<Component Value="33.21" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="168.77" NodeIdx="0" />
			<Component Value="64.61" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="0" NodeIdx="0" />
			<Component Value="12.06" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="161.41" NodeIdx="0" />
			<Component Value="117.22" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-36.8" NodeIdx="0" />
			<Component Value="36.8" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="163.71" NodeIdx="0" />
			<Component Value="125.11" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="0.62" NodeIdx="0" />
			<Component Value="-1.22" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="163.71" NodeIdx="0" />
			<Component Value="125.11" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="176.15" NodeIdx="0" />
			<Component Value="108.26" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="7.16" NodeIdx="0" />
			<Component Value="1.13" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="100.03" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-0.66" NodeIdx="0" />
			<Component Value="4.19" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="161.95" NodeIdx="0" />
			<Component Value="113.98" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="134.54" NodeIdx="0" />
			<Component Value="70.03" NodeIdx="1" />
			<Component Value="10" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-9.49" NodeIdx="0" />
			<Component Value="18.63" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="100.03" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-1.92" NodeIdx="0" />
			<Component Value="3.77" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="146.66" NodeIdx="0" />
			<Component Value="78.95" NodeIdx="1" />
			<Component Value="8" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-9.54" NodeIdx="0" />
			<Component Value="29.38" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="158.58" NodeIdx="0" />
			<Component Value="122.77" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="136.69" NodeIdx="0" />
			<Component Value="123.69" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-13.58" NodeIdx="0" />
			<Component Value="-2.15" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="13" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="201.11" NodeIdx="0" />
			<Component Value="63.4" NodeIdx="1" />
			<Component Value="7" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="9.49" NodeIdx="0" />
			<Component Value="18.63" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="165.11" NodeIdx="0" />
			<Component Value="116.28" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="201.11" NodeIdx="0" />
			<Component Value="63.4" NodeIdx="1" />
			<Component Value="7" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="7.83" NodeIdx="0" />
			<Component Value="15.36" NodeIdx="1" />
			<Component Value="7" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="187.74" NodeIdx="0" />
			<Component Value="105.86" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="7.16" NodeIdx="0" />
			<Component Value="1.13" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="118.2" NodeIdx="0" />
			<Component Value="89.63" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-46.38" NodeIdx="0" />
			<Component Value="23.63" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="171.61" NodeIdx="0" />