<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Map [
<!ELEMENT Map (Comment?,Link*)>
<!ATTLIST Map
          InpDim       CDATA #REQUIRED
          OutDim       CDATA #REQUIRED
          LinkAttrDim  CDATA #REQUIRED>
<!ELEMENT Comment (#PCDATA)>
<!ELEMENT Link (InputNode+,OutputNode+,LinkAttr+)>
<!ELEMENT InputNode (Component+)>
<!ATTLIST InputNode
    Dim         CDATA #REQUIRED>
<!ELEMENT OutputNode (Component+)>
<!ATTLIST OutputNode
    Dim         CDATA #REQUIRED>
<!ELEMENT LinkAttr (LinkAttrValue+)>
<!ATTLIST LinkAttr
    Dim         CDATA #REQUIRED>
<!ELEMENT Component EMPTY>
<!ATTLIST Component
    Value         CDATA #REQUIRED
    NodeIdx       CDATA #REQUIRED>
<!ELEMENT LinkAttrValue EMPTY>
<!ATTLIST LinkAttrValue
    LinkValue     CDATA #REQUIRED
    Idx           CDATA #REQUIRED>
]>
<Map InpDim="4" OutDim="4" LinkAttrDim="1">
	<Comment>
[1,0,320,0,240][1,-60,60,-53,53]
	</Comment>
	<Link>
		<InputNode Dim="4">
			<Component Value="185.36" NodeIdx="0" />
			<Component Value="85.08" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="9.76" NodeIdx="0" />
			<Component Value="7.09" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="158.58" NodeIdx="0" />
			<Component Value="122.77" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="174.91" NodeIdx="0" />
			<Component Value="25.82" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="9.49" NodeIdx="0" />
			<Component Value="18.63" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="174.63" NodeIdx="0" />
			<Component Value="112.54" NodeIdx="1" />
			<Component Value="13" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="6.46" NodeIdx="0" />
			<Component Value="3.29" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="176.15" NodeIdx="0" />
			<Component Value="108.26" NodeIdx="1" />
			<Component Value="14" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="6.46" NodeIdx="0" />
			<Component Value="3.29" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="164.87" NodeIdx="0" />
			<Component Value="89.24" NodeIdx="1" />
			<Component Value="116" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="2.72" NodeIdx="0" />
			<Component Value="8.38" NodeIdx="1" />
			<Component Value="17" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="138.38" NodeIdx="0" />
			<Component Value="53.47" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-19.11" NodeIdx="0" />
			<Component Value="37.52" NodeIdx="1" />
			<Component Value="29" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="76.21" NodeIdx="0" />
			<Component Value="106.72" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-32.619" NodeIdx="0" />
			<Component Value="5.16" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="8" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="5" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="125.08" NodeIdx="0" />
			<Component Value="94.63" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-14.72" NodeIdx="0" />
			<Component Value="4.78" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="187.82" NodeIdx="0" />
			<Component Value="34.37" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-44.24" NodeIdx="0" />
			<Component Value="32.14" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="110.03" NodeIdx="0" />
			<Component Value="145.45" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-20.66" NodeIdx="0" />
			<Component Value="-3.27" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="13" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="189.6" NodeIdx="0" />
			<Component Value="61.89" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="12.19" NodeIdx="0" />
			<Component Value="12.19" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="189.6" NodeIdx="0" />
			<Component Value="61.89" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="11.2" NodeIdx="0" />
			<Component Value="15.42" NodeIdx="1" />
			<Component Value="66" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="128.85" NodeIdx="0" />
			<Component Value="24.14" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-11.24" NodeIdx="0" />
			<Component Value="22.06" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="86.12" NodeIdx="0" />
			<Component Value="108.29" NodeIdx="1" />
			<Component Value="93" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-32.619" NodeIdx="0" />
			<Component Value="5.16" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="8" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="50.04" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="6.58" NodeIdx="0" />
			<Component Value="41.59" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="137.98" NodeIdx="0" />
			<Component Value="142.01" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-7.13" NodeIdx="0" />
			<Component Value="-5.18" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="137.98" NodeIdx="0" />
			<Component Value="142.01" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-8.38" NodeIdx="0" />
			<Component Value="-2.72" NodeIdx="1" />
			<Component Value="110" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="138.38" NodeIdx="0" />
			<Component Value="53.47" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-7.83" NodeIdx="0" />
			<Component Value="15.36" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="164.87" NodeIdx="0" />
			<Component Value="89.24" NodeIdx="1" />
			<Component Value="116" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="5.18" NodeIdx="0" />
			<Component Value="7.13" NodeIdx="1" />
			<Component Value="116" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="84.8" NodeIdx="0" />
			<Component Value="44.8" NodeIdx="1" />
			<Component Value="126" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-44.24" NodeIdx="0" />
			<Component Value="32.14" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="113.11" NodeIdx="0" />
			<Component Value="55.47" NodeIdx="1" />
			<Component Value="129" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-21.65" NodeIdx="0" />
			<Component Value="15.73" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="151.55" NodeIdx="0" />
			<Component Value="94.01" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-1.13" NodeIdx="0" />
			<Component Value="7.16" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="76.65" NodeIdx="0" />
			<Component Value="36.65" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-29.77" NodeIdx="0" />
			<Component Value="29.77" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="59.21" NodeIdx="0" />
			<Component Value="119.99" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-39.76" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="94.14" NodeIdx="0" />
			<Component Value="29.35" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-23.35" NodeIdx="0" />
			<Component Value="23.35" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="120.34" NodeIdx="0" />
			<Component Value="80.34" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-18.63" NodeIdx="0" />
			<Component Value="9.49" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="110.97" NodeIdx="0" />
			<Component Value="84.38" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-18.63" NodeIdx="0" />
			<Component Value="9.49" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="132.67" NodeIdx="0" />
			<Component Value="120" NodeIdx="1" />
			<Component Value="155" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-10.29" NodeIdx="0" />
			<Component Value="1.63" NodeIdx="1" />
			<Component Value="155" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="111.71" NodeIdx="0" />
			<Component Value="25.24" NodeIdx="1" />
			<Component Value="172" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-14.99" NodeIdx="0" />
			<Component Value="29.43" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="146.72" NodeIdx="0" />
			<Component Value="36.21" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-5.89" NodeIdx="0" />
			<Component Value="18.12" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="111.71" NodeIdx="0" />
			<Component Value="25.24" NodeIdx="1" />
			<Component Value="172" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-3.87" NodeIdx="0" />
			<Component Value="24.46" NodeIdx="1" />
			<Component Value="172" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="94.14" NodeIdx="0" />
			<Component Value="29.35" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-28.49" NodeIdx="0" />
			<Component Value="20.7" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="87.22" NodeIdx="0" />
			<Component Value="19.83" NodeIdx="1" />
			<Component Value="175" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-28.49" NodeIdx="0" />
			<Component Value="20.7" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="50.04" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-10.88" NodeIdx="0" />
			<Component Value="33.5" NodeIdx="1" />
			<Component Value="176" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="171.7" NodeIdx="0" />
			<Component Value="46.12" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="9.49" NodeIdx="0" />
			<Component Value="18.63" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="168.77" NodeIdx="0" />
			<Component Value="64.61" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="6.24" NodeIdx="0" />
			<Component Value="12.25" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="156.28" NodeIdx="0" />
			<Component Value="125.11" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="65.239" NodeIdx="0" />
			<Component Value="71.71" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-37.81" NodeIdx="0" />
			<Component Value="12.28" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="148.29" NodeIdx="0" />
			<Component Value="46.12" NodeIdx="1" />
			<Component Value="8" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-2.69" NodeIdx="0" />
			<Component Value="17.03" NodeIdx="1" />
			<Component Value="8" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="175.96" NodeIdx="0" />
			<Component Value="70.86" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="6.24" NodeIdx="0" />
			<Component Value="12.25" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160.48" NodeIdx="0" />
			<Component Value="116.91" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="76.84" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.63" NodeIdx="0" />
			<Component Value="10.29" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="100.76" NodeIdx="0" />
			<Component Value="38.46" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-29.77" NodeIdx="0" />
			<Component Value="29.77" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="135.35" NodeIdx="0" />
			<Component Value="44.14" NodeIdx="1" />
			<Component Value="15" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-7.83" NodeIdx="0" />
			<Component Value="15.36" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="117.8" NodeIdx="0" />
			<Component Value="98.49" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-14.72" NodeIdx="0" />
			<Component Value="4.78" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="157.22" NodeIdx="0" />
			<Component Value="118.58" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="65.82" NodeIdx="0" />
			<Component Value="134.91" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-39.76" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="174.91" NodeIdx="0" />
			<Component Value="25.82" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="11.24" NodeIdx="0" />
			<Component Value="22.06" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="113.88" NodeIdx="0" />
			<Component Value="73.88" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-18.63" NodeIdx="0" />
			<Component Value="9.49" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="167.4" NodeIdx="0" />
			<Component Value="73.22" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="5.16" NodeIdx="0" />
			<Component Value="32.619" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="176.68" NodeIdx="0" />
			<Component Value="103.31" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="6.46" NodeIdx="0" />
			<Component Value="3.29" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="176.05" NodeIdx="0" />
			<Component Value="97.89" NodeIdx="1" />
			<Component Value="7" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="6.46" NodeIdx="0" />
			<Component Value="3.29" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="100.76" NodeIdx="0" />
			<Component Value="38.46" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-23.35" NodeIdx="0" />
			<Component Value="23.35" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="65.82" NodeIdx="0" />
			<Component Value="105.08" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-39.76" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="155.63" NodeIdx="0" />
			<Component Value="111.44" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="68.33" NodeIdx="1" />
			<Component Value="13" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="10.88" NodeIdx="0" />
			<Component Value="33.5" NodeIdx="1" />
			<Component Value="13" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="143.31" NodeIdx="0" />
			<Component Value="136.68" NodeIdx="1" />
			<Component Value="14" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-5.13" NodeIdx="0" />
			<Component Value="-5.13" NodeIdx="1" />
			<Component Value="14" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="87.16" NodeIdx="0" />