<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Map [
<!ELEMENT Map (Comment?,Link*)>
<!ATTLIST Map
          InpDim       CDATA #REQUIRED
          OutDim       CDATA #REQUIRED
          LinkAttrDim  CDATA #REQUIRED>
<!ELEMENT Comment (#PCDATA)>
<!ELEMENT Link (InputNode+,OutputNode+,LinkAttr+)>
<!ELEMENT InputNode (Component+)>
<!ATTLIST InputNode
    Dim         CDATA #REQUIRED>
<!ELEMENT OutputNode (Component+)>
<!ATTLIST OutputNode
    Dim         CDATA #REQUIRED>
<!ELEMENT LinkAttr (LinkAttrValue+)>
<!ATTLIST LinkAttr
    Dim         CDATA #REQUIRED>
<!ELEMENT Component EMPTY>
<!ATTLIST Component
    Value         CDATA #REQUIRED
    NodeIdx       CDATA #REQUIRED>
<!ELEMENT LinkAttrValue EMPTY>
<!ATTLIST LinkAttrValue
    LinkValue     CDATA #REQUIRED
    Idx           CDATA #REQUIRED>
]>
<Map InpDim="4" OutDim="4" LinkAttrDim="1">
	<Comment>
[1,0,320,0,240][1,-60,60,-53,53]
	</Comment>
	<Link>
		<InputNode Dim="4">
			<Component Value="158.58" NodeIdx="0" />
			<Component Value="122.77" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="7" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="176.15" NodeIdx="0" />
			<Component Value="108.26" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="11" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="6.46" NodeIdx="0" />
			<Component Value="3.29" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="19" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="6" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="164.87" NodeIdx="0" />
			<Component Value="89.24" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="8" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="2.72" NodeIdx="0" />
			<Component Value="8.38" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="49" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="138.38" NodeIdx="0" />
			<Component Value="53.47" NodeIdx="1" />
			<Component Value="10" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-19.11" NodeIdx="0" />
			<Component Value="37.52" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="-2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="125.08" NodeIdx="0" />
			<Component Value="94.63" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="26" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-14.72" NodeIdx="0" />
			<Component Value="4.78" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="65" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="15" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="187.82" NodeIdx="0" />
			<Component Value="34.37" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-44.24" NodeIdx="0" />
			<Component Value="32.14" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="110.03" NodeIdx="0" />
			<Component Value="145.45" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="30" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-20.66" NodeIdx="0" />
			<Component Value="-3.27" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="112" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="18" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="189.6" NodeIdx="0" />
			<Component Value="61.89" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="14" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="12.19" NodeIdx="0" />
			<Component Value="12.19" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="18" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="8" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="189.6" NodeIdx="0" />
			<Component Value="61.89" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="14" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="11.2" NodeIdx="0" />
			<Component Value="15.42" NodeIdx="1" />
			<Component Value="66" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="137.98" NodeIdx="0" />
			<Component Value="142.01" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="19" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-8.38" NodeIdx="0" />
			<Component Value="-2.72" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="164.87" NodeIdx="0" />
			<Component Value="89.24" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="8" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="5.18" NodeIdx="0" />
			<Component Value="7.13" NodeIdx="1" />
			<Component Value="116" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="76.65" NodeIdx="0" />
			<Component Value="36.65" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-29.77" NodeIdx="0" />
			<Component Value="29.77" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="-5" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="156.28" NodeIdx="0" />
			<Component Value="125.11" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="6" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="148.29" NodeIdx="0" />
			<Component Value="46.12" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-2.69" NodeIdx="0" />
			<Component Value="17.03" NodeIdx="1" />
			<Component Value="8" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160.48" NodeIdx="0" />
			<Component Value="116.91" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="5" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="76.84" NodeIdx="1" />
			<Component Value="16" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.63" NodeIdx="0" />
			<Component Value="10.29" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="157.22" NodeIdx="0" />
			<Component Value="118.58" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="7" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="176.05" NodeIdx="0" />
			<Component Value="97.89" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="6.46" NodeIdx="0" />
			<Component Value="3.29" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="19" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="155.63" NodeIdx="0" />
			<Component Value="111.44" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="11" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="11" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="68.33" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="-3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="10.88" NodeIdx="0" />
			<Component Value="33.5" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="149.5" NodeIdx="0" />
			<Component Value="127.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="13" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="13" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="147.66" NodeIdx="0" />
			<Component Value="115.99" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="6" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="137.89" NodeIdx="0" />
			<Component Value="136.05" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-7.13" NodeIdx="0" />
			<Component Value="-5.18" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="17" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="151.44" NodeIdx="0" />
			<Component Value="115.63" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="10" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="10" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="149.28" NodeIdx="0" />
			<Component Value="98.97" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="-2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-1.13" NodeIdx="0" />
			<Component Value="7.16" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="153.67" NodeIdx="0" />
			<Component Value="120" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="8" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="8" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="144.03" NodeIdx="0" />
			<Component Value="70.86" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-6.58" NodeIdx="0" />
			<Component Value="41.59" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="170.49" NodeIdx="0" />
			<Component Value="127.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="14" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="13" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="144.03" NodeIdx="0" />
			<Component Value="70.86" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-13.75" NodeIdx="0" />
			<Component Value="42.33" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="167.62" NodeIdx="0" />
			<Component Value="130.49" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="7" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="152.59" NodeIdx="0" />
			<Component Value="73.22" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="0" NodeIdx="0" />
			<Component Value="44.51" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="129.24" NodeIdx="0" />
			<Component Value="124.87" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-19.06" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="164" NodeIdx="0" />
			<Component Value="132.33" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="12" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="12" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="147.66" NodeIdx="0" />
			<Component Value="124" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="8" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="8" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="152.54" NodeIdx="0" />
			<Component Value="134.63" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="18" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-4.19" NodeIdx="0" />
			<Component Value="-0.66" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="27" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="10" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="126.32" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="12" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="12" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="107.08" NodeIdx="0" />
			<Component Value="47.16" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-40.56" NodeIdx="0" />
			<Component Value="40.56" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="163.08" NodeIdx="0" />
			<Component Value="120.48" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="11" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="11" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="162.77" NodeIdx="0" />
			<Component Value="118.58" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="6" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="152.37" NodeIdx="0" />
			<Component Value="109.5" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="168.55" NodeIdx="0" />
			<Component Value="115.63" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="27" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="27" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="140.03" NodeIdx="0" />
			<Component Value="120" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="21" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-4.19" NodeIdx="0" />
			<Component Value="0.66" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="65" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="13" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="150.51" NodeIdx="0" />
			<Component Value="121.5" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="16" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="16" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="163.69" NodeIdx="0" />
			<Component Value="96.69" NodeIdx="1" />
			<Component Value="16" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="5.13" NodeIdx="0" />
			<Component Value="5.13" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="-2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="168.55" NodeIdx="0" />
			<Component Value="124.36" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="10" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="10" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="151.44" NodeIdx="0" />
			<Component Value="124.36" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="134.54" NodeIdx="0" />
			<Component Value="70.03" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-9.54" NodeIdx="0" />
			<Component Value="29.38" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="164.36" NodeIdx="0" />
			<Component Value="128.55" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="19" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="19" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="128.85" NodeIdx="0" />
			<Component Value="24.14" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-13.07" NodeIdx="0" />
			<Component Value="25.66" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="162.2" NodeIdx="0" />
			<Component Value="122.2" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="7" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="132.97" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="13" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-0.86" NodeIdx="0" />
			<Component Value="-2.65" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="33" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="107.08" NodeIdx="0" />
			<Component Value="47.16" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-26.16" NodeIdx="0" />
			<Component Value="36.01" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="161.41" NodeIdx="0" />
			<Component Value="117.22" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="6" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="156.3" NodeIdx="0" />
			<Component Value="143.3" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="8" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-3.36" NodeIdx="0" />
			<Component Value="-4.63" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="75" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="6" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="50.04" NodeIdx="1" />
			<Component Value="13" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-13.75" NodeIdx="0" />
			<Component Value="42.33" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="152.54" NodeIdx="0" />
			<Component Value="105.36" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-4.63" NodeIdx="0" />
			<Component Value="3.36" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="18" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="155.99" NodeIdx="0" />
			<Component Value="132.33" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="9" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="621" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="9" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="153.89" NodeIdx="0" />
			<Component Value="81.42" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="0" NodeIdx="0" />
			<Component Value="39.76" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>