<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Map [
<!ELEMENT Map (Comment?,Link*)>
<!ATTLIST Map
          InpDim       CDATA #REQUIRED
          OutDim       CDATA #REQUIRED
          LinkAttrDim  CDATA #REQUIRED>
<!ELEMENT Comment (#PCDATA)>
<!ELEMENT Link (InputNode+,OutputNode+,LinkAttr+)>
<!ELEMENT InputNode (Component+)>
<!ATTLIST InputNode
    Dim         CDATA #REQUIRED>
<!ELEMENT OutputNode (Component+)>
<!ATTLIST OutputNode
    Dim         CDATA #REQUIRED>
<!ELEMENT LinkAttr (LinkAttrValue+)>
<!ATTLIST LinkAttr
    Dim         CDATA #REQUIRED>
<!ELEMENT Component EMPTY>
<!ATTLIST Component
    Value         CDATA #REQUIRED
    NodeIdx       CDATA #REQUIRED>
<!ELEMENT LinkAttrValue EMPTY>
<!ATTLIST LinkAttrValue
    LinkValue     CDATA #REQUIRED
    Idx           CDATA #REQUIRED>
]>
<Map InpDim="4" OutDim="4" LinkAttrDim="1">
	<Comment>
[1,0,320,0,240][1,-60,60,-53,53]
	</Comment>
	<Link>
		<InputNode Dim="4">
			<Component Value="152.37" NodeIdx="0" />
			<Component Value="109.5" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="250" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="7" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="76.84" NodeIdx="1" />
			<Component Value="103" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-7.34" NodeIdx="0" />
			<Component Value="46.39" NodeIdx="1" />
			<Component Value="11" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="100.01" NodeIdx="0" />
			<Component Value="60.01" NodeIdx="1" />
			<Component Value="21" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="0" NodeIdx="0" />
			<Component Value="35.22" NodeIdx="1" />
			<Component Value="20" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="100.01" NodeIdx="0" />
			<Component Value="60.01" NodeIdx="1" />
			<Component Value="21" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-13.07" NodeIdx="0" />
			<Component Value="25.66" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="226.64" NodeIdx="0" />
			<Component Value="86.04" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="32.14" NodeIdx="0" />
			<Component Value="44.24" NodeIdx="1" />
			<Component Value="28" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="178.72" NodeIdx="0" />
			<Component Value="62.37" NodeIdx="1" />
			<Component Value="36" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="35.34" NodeIdx="0" />
			<Component Value="48.64" NodeIdx="1" />
			<Component Value="34" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="178.72" NodeIdx="0" />
			<Component Value="62.37" NodeIdx="1" />
			<Component Value="36" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="8.26" NodeIdx="0" />
			<Component Value="25.45" NodeIdx="1" />
			<Component Value="36" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="226.64" NodeIdx="0" />
			<Component Value="86.04" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="41.59" NodeIdx="0" />
			<Component Value="6.58" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="113.22" NodeIdx="0" />
			<Component Value="112.59" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-10.29" NodeIdx="0" />
			<Component Value="-1.63" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="27" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="185.45" NodeIdx="0" />
			<Component Value="70.03" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="0" NodeIdx="0" />
			<Component Value="39.76" NodeIdx="1" />
			<Component Value="53" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="185.45" NodeIdx="0" />
			<Component Value="70.03" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="11.24" NodeIdx="0" />
			<Component Value="22.06" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="216.59" NodeIdx="0" />
			<Component Value="78.88" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="39.76" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="151.22" NodeIdx="0" />
			<Component Value="64.61" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="3.87" NodeIdx="0" />
			<Component Value="24.46" NodeIdx="1" />
			<Component Value="91" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="167.4" NodeIdx="0" />
			<Component Value="73.22" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="12.28" NodeIdx="0" />
			<Component Value="37.81" NodeIdx="1" />
			<Component Value="101" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="167.4" NodeIdx="0" />
			<Component Value="73.22" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="2.69" NodeIdx="0" />
			<Component Value="17.03" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="76.84" NodeIdx="1" />
			<Component Value="103" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="2.69" NodeIdx="0" />
			<Component Value="17.03" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="212.88" NodeIdx="0" />
			<Component Value="67.11" NodeIdx="1" />
			<Component Value="119" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="18.15" NodeIdx="0" />
			<Component Value="24.99" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="224.52" NodeIdx="0" />
			<Component Value="73.11" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="18.15" NodeIdx="0" />
			<Component Value="24.99" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="232.83" NodeIdx="0" />
			<Component Value="67.08" NodeIdx="1" />
			<Component Value="19" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="18.15" NodeIdx="0" />
			<Component Value="24.99" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="201.11" NodeIdx="0" />
			<Component Value="63.4" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="9.54" NodeIdx="0" />
			<Component Value="29.38" NodeIdx="1" />
			<Component Value="119" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="212.88" NodeIdx="0" />
			<Component Value="67.11" NodeIdx="1" />
			<Component Value="119" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="9.54" NodeIdx="0" />
			<Component Value="29.38" NodeIdx="1" />
			<Component Value="119" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="216.59" NodeIdx="0" />
			<Component Value="78.88" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="5.16" NodeIdx="0" />
			<Component Value="32.619" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="-5" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="121.42" NodeIdx="0" />
			<Component Value="113.89" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-10.29" NodeIdx="0" />
			<Component Value="-1.63" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="27" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="141.27" NodeIdx="0" />
			<Component Value="177.62" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="-2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-5.86" NodeIdx="0" />
			<Component Value="-37" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="-2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="155.99" NodeIdx="0" />
			<Component Value="107.66" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="250" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="5" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="157.43" NodeIdx="0" />
			<Component Value="103.77" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="15" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="0.86" NodeIdx="0" />
			<Component Value="2.65" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="17" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="8" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="187.32" NodeIdx="0" />
			<Component Value="120" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="11" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="7.16" NodeIdx="0" />
			<Component Value="1.13" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="24" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="7" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="167.45" NodeIdx="0" />
			<Component Value="105.36" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="13" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="250" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="9" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="187.32" NodeIdx="0" />
			<Component Value="120" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="11" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="4.63" NodeIdx="0" />
			<Component Value="-3.36" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="229.95" NodeIdx="0" />
			<Component Value="120" NodeIdx="1" />
			<Component Value="24" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="35.22" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="24" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="158.49" NodeIdx="0" />
			<Component Value="110.51" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="250" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="6" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="149.28" NodeIdx="0" />
			<Component Value="98.97" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="13" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-3.36" NodeIdx="0" />
			<Component Value="4.63" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="32" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="8" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="120.34" NodeIdx="0" />
			<Component Value="80.34" NodeIdx="1" />
			<Component Value="17" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="5.16" NodeIdx="0" />
			<Component Value="32.619" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="-5" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="101.89" NodeIdx="0" />
			<Component Value="90.39" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-15.36" NodeIdx="0" />
			<Component Value="7.83" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="232.83" NodeIdx="0" />
			<Component Value="67.08" NodeIdx="1" />
			<Component Value="19" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="24.99" NodeIdx="0" />
			<Component Value="18.15" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="110.97" NodeIdx="0" />
			<Component Value="84.38" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="9" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-15.42" NodeIdx="0" />
			<Component Value="11.2" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="9" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="6" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="107.11" NodeIdx="0" />
			<Component Value="67.11" NodeIdx="1" />
			<Component Value="17" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-15.29" NodeIdx="0" />
			<Component Value="47.06" NodeIdx="1" />
			<Component Value="21" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="132.38" NodeIdx="0" />
			<Component Value="92.38" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-7.37" NodeIdx="0" />
			<Component Value="7.37" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="8" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="206.11" NodeIdx="0" />
			<Component Value="73.88" NodeIdx="1" />
			<Component Value="23" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="10.88" NodeIdx="0" />
			<Component Value="33.5" NodeIdx="1" />
			<Component Value="23" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="173.33" NodeIdx="0" />
			<Component Value="78.95" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="2.69" NodeIdx="0" />
			<Component Value="17.03" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="182.1" NodeIdx="0" />
			<Component Value="103.94" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="7.13" NodeIdx="0" />
			<Component Value="5.18" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="40" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="162.2" NodeIdx="0" />
			<Component Value="117.79" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="250" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="182.1" NodeIdx="0" />
			<Component Value="103.94" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="5.13" NodeIdx="0" />
			<Component Value="5.13" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="153.2" NodeIdx="0" />
			<Component Value="113.2" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="8" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="250" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="8" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="134.63" NodeIdx="0" />
			<Component Value="85.08" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-6.24" NodeIdx="0" />
			<Component Value="12.25" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="209.02" NodeIdx="0" />
			<Component Value="84.38" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="14.79" NodeIdx="0" />
			<Component Value="14.79" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="134.63" NodeIdx="0" />
			<Component Value="85.08" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-4.73" NodeIdx="0" />
			<Component Value="9.28" NodeIdx="1" />
			<Component Value="7" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="166.17" NodeIdx="0" />
			<Component Value="101" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="14" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="4.63" NodeIdx="0" />
			<Component Value="3.36" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="14" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="9" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="138.97" NodeIdx="0" />
			<Component Value="130.71" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-5.13" NodeIdx="0" />
			<Component Value="-5.13" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="18" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="138.97" NodeIdx="0" />
			<Component Value="130.71" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-3.36" NodeIdx="0" />
			<Component Value="-4.63" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="99.4" NodeIdx="0" />
			<Component Value="119.99" NodeIdx="1" />
			<Component Value="11" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-14.72" NodeIdx="0" />
			<Component Value="4.78" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="163.71" NodeIdx="0" />
			<Component Value="114.88" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="250" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="5" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="107.02" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="250" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="7" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="153.98" NodeIdx="0" />
			<Component Value="118.04" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="6" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="250" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="6" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="107.11" NodeIdx="0" />
			<Component Value="67.11" NodeIdx="1" />
			<Component Value="17" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-10.88" NodeIdx="0" />
			<Component Value="33.5" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="-2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="148.26" NodeIdx="0" />
			<Component Value="103.84" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-3.36" NodeIdx="0" />
			<Component Value="4.63" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="32" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="110.86" NodeIdx="0" />
			<Component Value="104.03" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="10" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-13.58" NodeIdx="0" />
			<Component Value="2.15" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="19" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="6" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="158.58" NodeIdx="0" />
			<Component Value="122.77" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="250" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">