<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Map [
<!ELEMENT Map (Comment?,Link*)>
<!ATTLIST Map
          InpDim       CDATA #REQUIRED
          OutDim       CDATA #REQUIRED
          LinkAttrDim  CDATA #REQUIRED>
<!ELEMENT Comment (#PCDATA)>
<!ELEMENT Link (InputNode+,OutputNode+,LinkAttr+)>
<!ELEMENT InputNode (Component+)>
<!ATTLIST InputNode
    Dim         CDATA #REQUIRED>
<!ELEMENT OutputNode (Component+)>
<!ATTLIST OutputNode
    Dim         CDATA #REQUIRED>
<!ELEMENT LinkAttr (LinkAttrValue+)>
<!ATTLIST LinkAttr
    Dim         CDATA #REQUIRED>
<!ELEMENT Component EMPTY>
<!ATTLIST Component
    Value         CDATA #REQUIRED
    NodeIdx       CDATA #REQUIRED>
<!ELEMENT LinkAttrValue EMPTY>
<!ATTLIST LinkAttrValue
    LinkValue     CDATA #REQUIRED
    Idx           CDATA #REQUIRED>
]>
<Map InpDim="4" OutDim="4" LinkAttrDim="1">
	<Comment>
[1,0,320,0,240][1,-60,60,-53,53]
	</Comment>
	<Link>
		<InputNode Dim="4">
			<Component Value="126.51" NodeIdx="0" />
			<Component Value="153.48" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-9.72" NodeIdx="0" />
			<Component Value="-9.72" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="9" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="149.5" NodeIdx="0" />
			<Component Value="112.37" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="78.46" NodeIdx="0" />
			<Component Value="179.23" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-40.03" NodeIdx="0" />
			<Component Value="29.08" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="78.46" NodeIdx="0" />
			<Component Value="179.23" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-21.65" NodeIdx="0" />
			<Component Value="-15.73" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="-2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="87.16" NodeIdx="0" />
			<Component Value="172.91" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-37.52" NodeIdx="0" />
			<Component Value="-19.11" NodeIdx="1" />
			<Component Value="8" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="87.16" NodeIdx="0" />
			<Component Value="172.91" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-41.85" NodeIdx="0" />
			<Component Value="-21.32" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="126.51" NodeIdx="0" />
			<Component Value="153.48" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-6.24" NodeIdx="0" />
			<Component Value="-12.25" NodeIdx="1" />
			<Component Value="14" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="80.24" NodeIdx="0" />
			<Component Value="119.99" NodeIdx="1" />
			<Component Value="8" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-26.76" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="26" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="164.36" NodeIdx="0" />
			<Component Value="111.44" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="93.35" NodeIdx="0" />
			<Component Value="153.95" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="21" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-18.63" NodeIdx="0" />
			<Component Value="-9.49" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="33" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="13" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="103.4" NodeIdx="0" />
			<Component Value="78.88" NodeIdx="1" />
			<Component Value="24" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-15.42" NodeIdx="0" />
			<Component Value="11.2" NodeIdx="1" />
			<Component Value="24" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="80.24" NodeIdx="0" />
			<Component Value="119.99" NodeIdx="1" />
			<Component Value="8" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-28.44" NodeIdx="0" />
			<Component Value="-4.5" NodeIdx="1" />
			<Component Value="27" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="164.36" NodeIdx="0" />
			<Component Value="128.55" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.64" NodeIdx="0" />
			<Component Value="-2.25" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="164.36" NodeIdx="0" />
			<Component Value="128.55" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="84.14" NodeIdx="0" />
			<Component Value="95.35" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-51.41" NodeIdx="0" />
			<Component Value="8.14" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="130.39" NodeIdx="0" />
			<Component Value="61.89" NodeIdx="1" />
			<Component Value="7" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-36.01" NodeIdx="0" />
			<Component Value="26.16" NodeIdx="1" />
			<Component Value="20" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="141" NodeIdx="0" />
			<Component Value="113.82" NodeIdx="1" />
			<Component Value="15" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-6.46" NodeIdx="0" />
			<Component Value="3.29" NodeIdx="1" />
			<Component Value="19" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="104.61" NodeIdx="0" />
			<Component Value="128.77" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-15.47" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="36" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="95.47" NodeIdx="0" />
			<Component Value="73.11" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-18.46" NodeIdx="0" />
			<Component Value="13.41" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="95.47" NodeIdx="0" />
			<Component Value="73.11" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="3" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-32.16" NodeIdx="0" />
			<Component Value="23.37" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="143.77" NodeIdx="0" />
			<Component Value="117.43" NodeIdx="1" />
			<Component Value="19" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-6.46" NodeIdx="0" />
			<Component Value="3.29" NodeIdx="1" />
			<Component Value="19" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="149.17" NodeIdx="0" />
			<Component Value="153.33" NodeIdx="1" />
			<Component Value="20" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-5.18" NodeIdx="0" />
			<Component Value="-7.13" NodeIdx="1" />
			<Component Value="20" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="99.4" NodeIdx="0" />
			<Component Value="119.99" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="10" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-15.47" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="36" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="6" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="158.58" NodeIdx="0" />
			<Component Value="122.77" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="104.61" NodeIdx="0" />
			<Component Value="111.22" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-15.47" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="36" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="158.04" NodeIdx="0" />
			<Component Value="113.98" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="86.12" NodeIdx="0" />
			<Component Value="108.29" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-44.51" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="134.01" NodeIdx="0" />
			<Component Value="111.55" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="9" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-7.16" NodeIdx="0" />
			<Component Value="1.13" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="13" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="6" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="147.02" NodeIdx="0" />
			<Component Value="120" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="147.32" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.63" NodeIdx="0" />
			<Component Value="-10.29" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="107.11" NodeIdx="0" />
			<Component Value="67.11" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-56.07" NodeIdx="0" />
			<Component Value="28.57" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="68.33" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="2.15" NodeIdx="0" />
			<Component Value="13.58" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="9" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="152.59" NodeIdx="0" />
			<Component Value="73.22" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="4" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="2.15" NodeIdx="0" />
			<Component Value="13.58" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="9" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="107.11" NodeIdx="0" />
			<Component Value="67.11" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-57.18" NodeIdx="0" />
			<Component Value="18.57" NodeIdx="1" />
			<Component Value="14" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="84.41" NodeIdx="0" />
			<Component Value="81.48" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="-2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-28.49" NodeIdx="0" />
			<Component Value="20.7" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="116.84" NodeIdx="0" />
			<Component Value="120" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-8.38" NodeIdx="0" />
			<Component Value="-2.72" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="8" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="87.16" NodeIdx="0" />
			<Component Value="67.08" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-36.01" NodeIdx="0" />
			<Component Value="26.16" NodeIdx="1" />
			<Component Value="20" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160.48" NodeIdx="0" />
			<Component Value="123.08" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="84.14" NodeIdx="0" />
			<Component Value="95.35" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-33.5" NodeIdx="0" />
			<Component Value="10.88" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="125.08" NodeIdx="0" />
			<Component Value="145.36" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-9.72" NodeIdx="0" />
			<Component Value="-9.72" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="9" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="87.16" NodeIdx="0" />
			<Component Value="172.91" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-57.18" NodeIdx="0" />
			<Component Value="-18.57" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="80.24" NodeIdx="0" />
			<Component Value="119.99" NodeIdx="1" />
			<Component Value="8" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-49.48" NodeIdx="0" />
			<Component Value="0" NodeIdx="1" />
			<Component Value="5" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="93.35" NodeIdx="0" />
			<Component Value="86.04" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-37" NodeIdx="0" />
			<Component Value="5.86" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="158.04" NodeIdx="0" />
			<Component Value="126.01" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="132.97" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="87.16" NodeIdx="0" />
			<Component Value="172.91" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-47.06" NodeIdx="0" />
			<Component Value="-15.29" NodeIdx="1" />
			<Component Value="7" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="157.43" NodeIdx="0" />
			<Component Value="136.22" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="-1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="163.69" NodeIdx="0" />
			<Component Value="96.69" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.63" NodeIdx="0" />
			<Component Value="10.29" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="15" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="87.16" NodeIdx="0" />
			<Component Value="172.91" NodeIdx="1" />
			<Component Value="6" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-51.41" NodeIdx="0" />
			<Component Value="-8.14" NodeIdx="1" />
			<Component Value="0" NodeIdx="2" />
			<Component Value="-1" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="100.01" NodeIdx="0" />
			<Component Value="60.01" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-28.49" NodeIdx="0" />
			<Component Value="20.7" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="153.67" NodeIdx="0" />
			<Component Value="120" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="2" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="2" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="100.01" NodeIdx="0" />
			<Component Value="60.01" NodeIdx="1" />
			<Component Value="4" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-23.35" NodeIdx="0" />
			<Component Value="23.35" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="154.88" NodeIdx="0" />
			<Component Value="123.71" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="107.11" NodeIdx="0" />
			<Component Value="67.11" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="-9.54" NodeIdx="0" />
			<Component Value="29.38" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="0" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="0" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="92.67" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="7" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.63" NodeIdx="0" />
			<Component Value="10.29" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="15" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="4" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="171.66" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="5" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="0" NodeIdx="0" />
			<Component Value="-15.47" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="16" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="3" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="158.49" NodeIdx="0" />
			<Component Value="129.479" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="1.22" NodeIdx="0" />
			<Component Value="0.62" NodeIdx="1" />
			<Component Value="1" NodeIdx="2" />
			<Component Value="41" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="160" NodeIdx="0" />
			<Component Value="180.59" NodeIdx="1" />
			<Component Value="2" NodeIdx="2" />
			<Component Value="1" NodeIdx="3" />
		</InputNode>
		<OutputNode Dim="4">
			<Component Value="0" NodeIdx="0" />
			<Component Value="-15.47" NodeIdx="1" />
			<Component Value="3" NodeIdx="2" />
			<Component Value="16" NodeIdx="3" />
		</OutputNode>
		<LinkAttr Dim="1">
			<LinkAttrValue LinkValue="1" Idx="0" />
		</LinkAttr>
	</Link>
	<Link>
		<InputNode Dim="4">
			<Component Value="76.21" NodeIdx="0" />